# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
      - Release/*
      - Hotfix/*

pool:
  name: IATec-Builds-Agents-Linux

variables:
  - group: nuget-credentials

steps:
  - task: Bash@3
    displayName: 'Rename .npmrc.pipeline to .npmrc'
    inputs:
      targetType: 'inline'
      script: 'mv .npmrc.pipeline .npmrc'

  - task: replacetokens@6
    displayName: 'Replace variables in .npmrc'
    inputs:
      targetFiles: '.npmrc'
      encoding: 'auto'
      writeBOM: true
      actionOnMissing: 'warn'
      keepToken: false
      tokenPrefix: '#{'
      tokenSuffix: '}#'
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '20.x'

  - task: Npm@1
    displayName: Install
    inputs:
      command: 'install'
      workingDir: '$(Build.SourcesDirectory)'
    env:
      NPM_CONFIG_FORCE: true
      NPM_CONFIG_LEGACY_PEER_DEPS: true

  - task: Npm@1
    displayName: Build
    inputs:
      command: 'custom'
      workingDir: '$(Build.SourcesDirectory)'
      customCommand: 'run build-storybook'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'dist/iatec.standard.web-ui.angular'
      ArtifactName: 'files'
      publishLocation: 'Container'
